[build]
command = "yarn frames:build"
publish = "packages/webdemo/dist"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF packages/webdemo"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200
