[build]
# publish = "packages/webapp/dist"
publish = "dist"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF packages/webapp"

[context.mainnet]
# command = "yarn workspace webapp build-mainnet"
command = "yarn build-mainnet"

[context.sepolia]
# command = "yarn workspace webapp build-sepolia"
command = "yarn build-sepolia"

[[redirects]]
from = "http://app.nns.xyz/*"
to = "https://nns.xyz/:splat"
status = 301
force = true

[[redirects]]
from = "https://app.nns.xyz/*"
to = "https://nns.xyz/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
