[build]
command = "yarn webapp:build"
publish = "packages/webapp/dist"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF packages/webapp"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200
