sudo: required

dist: trusty

language: node_js

node_js:
  - '14'

cache:
  yarn: true

matrix:
  allow_failures:
    #
jobs:
  include:
    - stage: test
      name: 'Test'
      install:
        - yarn
      script: 'yarn test'

stages:
  - name: test

notifications:
  email: false
